export default {
  // logIn status
  LOGIN_FALIED: 'LOGIN_FALIED',
  LOGIN_SUCCESSFULL: 'LOGIN_SUCCESSFULL',

  // loading animation status
  SHOW_LOADING_ANIMATION: 'SHOW_LOADING_ANIMATION',
  HIDE_LOADING_ANIMATION: 'HIDE_LOADING_ANIMATION',
  // fetch homepage data
  FETCH_DATA_FOR_HOME_PAGE: 'FETCH_DATA_FOR_HOME_PAGE',
  FETCH_DATA_FOR_HOME_PAGE_SUCCESSFUL: 'FETCH_DATA_FOR_HOME_PAGE_SUCCESSFUL',
  FETCH_DATA_FOR_HOME_PAGE_FAILED: 'FETCH_DATA_FOR_HOME_PAGE_SUCCESSFUL'
};
